// Code generated by "stringer -type=PathType"; DO NOT EDIT.

package fs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[IsFile-1]
	_ = x[IsDirectory-2]
}

const _PathType_name = "NoneIsFileIsDirectory"

var _PathType_index = [...]uint8{0, 4, 10, 21}

func (i PathType) String() string {
	if i < 0 || i >= PathType(len(_PathType_index)-1) {
		return "PathType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PathType_name[_PathType_index[i]:_PathType_index[i+1]]
}
