// Code generated by "stringer -type=Task"; DO NOT EDIT.

package lib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Invalid-1]
	_ = x[Clone-2]
	_ = x[Pull-3]
}

const _Task_name = "UnknownInvalidClonePull"

var _Task_index = [...]uint8{0, 7, 14, 19, 23}

func (i Task) String() string {
	if i < 0 || i >= Task(len(_Task_index)-1) {
		return "Task(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Task_name[_Task_index[i]:_Task_index[i+1]]
}
