// Code generated by "stringer -type=Task"; DO NOT EDIT.

package lib

import (
	"fmt"
	"testing"
)

func TestTask_String(t *testing.T) {
	tests := []struct {
		i    Task
		want string
	}{
		{ Unknown, "Unknown" },
		{ Invalid, "Invalid" },
		{ Clone, "Clone" },
		{ Pull, "Pull" },
		{ 42, "Task(42)" },
	}
	for _, tt := range tests {
		t.Run(fmt.Sprintf("Task %v", tt.want), func(t *testing.T) {
			if got := tt.i.String(); got != tt.want {
				t.Errorf("Task.String() = %v, want %v", got, tt.want)
			}
		})
	}
}
